// CHANGE VALUES HERE
export const MAX_BOOKING_HOURS = 5;

// CHANGE VALUES HERE
export const MAX_BOOKINGS_PER_DAY = 2;

// CHANGE VALUES HERE
export const MAX_SIMULTANEOUS_VEHICLES = 2;

// CHANGE VALUES HERE
export const ALLOW_FUTURE_BOOKINGS = true;

// CHANGE VALUES HERE
export const MAX_ADVANCE_BOOKING_DAYS = 2;

// CHANGE VALUES HERE
export const HANDOVER_BUFFER_MINUTES = 15;

// CHANGE VALUES HERE
export const ADMIN_CAN_OVERRIDE_ADVANCE_LIMIT = true;

// CHANGE VALUES HERE
export const DEFAULT_COORDINATOR_NAME = "Vehicle Coordinator";

// CHANGE VALUES HERE
export const DEFAULT_COORDINATOR_NUMBER = "98XXXXXXXX";

// CHANGE VALUES HERE
export const REQUIRE_MOBILE_CONFIRMATION_BEFORE_COMPLETION = true;

